In [2]:
from google.cloud import bigquery
import pandas as pd

project_id = "centered-sight-492614-f0"
json_path =  "/home/khanhdo/Documents/project/bigdata_mining/preprocessing/bigquery.json"
client = bigquery.Client.from_service_account_json(json_path, project = project_id)

/home/khanhdo/anaconda3/envs/spark_lab/lib/python3.10/site-packages/google/api_core/_python_version_support.py:263: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777974994.406264    4978 instrument.cc:563] Metric with name 'grpc.resource_quota.calls_dropped' registered more than once. Ignoring later registration.
E0000 00:00:1777974994.406310    4978 instrument.cc:563] Metric with name 'grpc.resource_quota.calls_rejected' registered more than once. Ignoring later registration.
E0000 00:00:1777974994.406314    4978 instrument.cc:563] Metric with name 'grpc.resource_quota.connections_dropped' registered more than once. Ignoring later registration.
E0000 00:00:1777974994.406316    4978 instrument.cc:563] Metric with name 'grpc.resource_quota.instantaneous_memory_pressure' registered more than once. Ignoring later registration.
E0000 00:00:1777974994.406319    4978 instrument.cc:563] Metric with name 'grpc.resource_quota.memory_pressure_control_value' registered more than once. Ignoring later registration.
/home/khanhdo/anaconda3/envs/spark_lab/lib/python3.10/site-packages/google/api_core/_python_version_support.py:263: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.bigquery_storage_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.bigquery_storage_v1 past that date.
  warnings.warn(message, FutureWarning)

In [5]:
query_tokens = """
select 
    address,
    symbol,
    name,
    decimals,
    total_supply
from `bigquery-public-data.crypto_ethereum.tokens`
where symbol IS NOT NULL 
    AND name IS NOT NULL
    AND decimals IS NOT NULL
    AND total_supply IS NOT NULL
    and safe_cast(total_supply AS NUMERIC) > 0
"""
df_tokens = client.query(query_tokens).to_dataframe()
df_tokens.head()

,address,symbol,name,decimals,total_supply
0,0x71ff01d3fb4d002738aa5a64db0d9e5b19f176de,SuperOX,SOX,4,8000000000000
1,0xe2f9af33fa4a43f21125d214452bf79b7226326c,OX,OX Coin,4,180000000000000
2,0x90c9134b62c7d42e4bf97a80f9c37ff1bf4eb52a,USD,USD,4,100000000
3,0x6a6603015654bbd41a50efdb73773107d7ecad9d,USD,USD,8,10000000
4,0xc3db38e3269ffa8cc066d10e9b01d30f04c86a7e,USD,USD,8,100000000

In [6]:
df_tokens.count()

address         174014
symbol          174014
name            174014
decimals        174014
total_supply    174014
dtype: int64

In [3]:
query_token_transfers = """
SELECT
    token_address,
    from_address,  
    to_address,
    value,
    transaction_hash,
    block_timestamp
FROM `bigquery-public-data.crypto_ethereum.token_transfers`
WHERE
    DATE(block_timestamp) >= "2026-02-15" and date(block_timestamp) < "2026-03-01"
    AND value != '0'
    AND to_address IS NOT NULL
    AND to_address != '0x0000000000000000000000000000000000000000' --Loai bo giao dich chet
"""
df_token_transfers = client.query(query_token_transfers).to_dataframe()
df_token_transfers.head()

,token_address,from_address,to_address,value,transaction_hash,block_timestamp
0,0x43a28c691c5c9c5f5431f063dd16df8fb36196b5,0x14fc6b5ff154b007ae7912150697144e4d1fc0a4,0xca139da2546227c71ad0c7fa491e95d72b1cfa49,12820973060571405,0xa3d69502b6e3ea3cf038db4b341c45241beaf221a15a...,2026-02-17 15:26:11+00:00
1,0x40d16fc0246ad3160ccc09b8d0d3a2cd28ae6c2f,0x52aa899454998be5b000ad077a46bbe360f4e497,0x6a000f20005980200259b80c5102003040001068,60004101646403424000000,0x03ce1f5198394612951238ae0b0e0b3ea87e8ed400bd...,2026-02-23 16:43:35+00:00
2,0x34a7fff7f05ba6bc76a9dc0d3d694103600238a1,0xbadbb1de95b5f333623ebece7026932fa5039ee6,0x07a52a654c887e5939475569831e0065dcd25e97,46000000000,0x0df7ba344bf2d341434c2818ed24581bee9186c69e70...,2026-02-20 23:32:59+00:00
3,0xd94da22ca133bcee2702728e483593153551aabc,0x4d9695216cf00e63dba76b478049481441e0aaa8,0xdf8f8af35e2cbef1c695e46aeb462041d174fe0d,105000000000000000,0x9362d91857a6247722167e6f8da156d10b766247ea57...,2026-02-22 12:46:11+00:00
4,0x3c60e0a1808da8b0ca6bf289290e8acb9b89b491,0x80ed9aa82d4d709a9f556892061d7fd4675730a4,0xbc1d9760bd6ca468ca9fb5ff2cfbeac35d86c973,8822714423899686573352,0xec7cc551646b990811f6dec6627b640129c4b88e1121...,2026-02-22 14:41:59+00:00

In [5]:
df_token_transfers.to_parquet( "/home/khanhdo/Documents/project/bigdata_mining/data_ingestion/token_transfers_t2_2.parquet",index=False)

print("Data has been saved to Parquet files.")

Data has been saved to Parquet files.

In [4]:
df_token_transfers.count()

token_address       44710335
from_address        44710335
to_address          44710335
value               44710335
transaction_hash    44710335
block_timestamp     44710335
dtype: int64

In [2]:
df_contracts = client.query("""
SELECT 
    address, 
    is_erc20, 
    is_erc721
FROM `bigquery-public-data.crypto_ethereum.contracts`
WHERE 
   date(block_timestamp) >= "2023-01-01" and date(block_timestamp) < "2026-04-01"
""").to_dataframe()

df_contracts.head()

                                      address  is_erc20  is_erc721
0  0xbede08fbe4d1c72814c35df89f550c175683f019     False      False
1  0xca6ae25d8409feeddf7ad4f74daf80226e289773     False      False
2  0xe99dd8d991be9ff81d31fb699429f174c224ec51     False      False
3  0x74527f97cc8b02bf92f54c51b14b00effb726e04     False      False
4  0x1b197a05c482ef0e79e204982d4b3f58294f619e     False      False

In [3]:
df_contracts.count()

address      42809126
is_erc20     42809126
is_erc721    42809126
dtype: int64

In [4]:
df_contracts.to_parquet( "/home/khanhdo/Documents/project/bigdata_mining/data_ingestion/contracts_2.parquet",index=False)